on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ip-128-199-28-33.server.weavers-web.com
        username: FOl53g9Q3chM3njVHi
        password: ${{ secrets.SLEEPEASY_PASSWORD }}